import React, { useState } from 'react';
import { 
  Database, 
  Download, 
  Upload, 
  FileSpreadsheet, 
  Check, 
  AlertCircle, 
  Printer, 
  RefreshCw,
  HardDriveDownload,
  Github,
  Globe
} from 'lucide-react';
import { useQAData } from '../context/QADataContext';
import { useThemeLanguage } from '../context/ThemeLanguageContext';
import { GitHubPagesModal } from './GitHubPagesModal';

export const BackupRecoveryModal: React.FC = () => {
  const { 
    exportBackupJSON, 
    exportIssuesCSV, 
    restoreFromJSON, 
    websites, 
    activeWebsite, 
    issues, 
    teamMembers 
  } = useQAData();
  
  const { t, language } = useThemeLanguage();

  const [restoreSuccess, setRestoreSuccess] = useState<string | null>(null);
  const [restoreError, setRestoreError] = useState<string | null>(null);
  const [showGhModal, setShowGhModal] = useState(false);

  const handleDownloadJSON = () => {
    const jsonStr = exportBackupJSON();
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ard_qa_backup_${activeWebsite?.id || 'all'}_${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadCSV = () => {
    const csvStr = exportIssuesCSV();
    const blob = new Blob([csvStr], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ard_qa_issues_${activeWebsite?.id || 'export'}_${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleRestoreFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    setRestoreSuccess(null);
    setRestoreError(null);

    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      const success = restoreFromJSON(content);
      if (success) {
        setRestoreSuccess(`Successfully restored database snapshot from ${file.name}`);
      } else {
        setRestoreError('Invalid backup file. Ensure the file was generated by ARD Test & Debug Systems.');
      }
    };
    reader.readAsText(file);
  };

  const handlePrintAuditReport = () => {
    window.print();
  };

  return (
    <div className="max-w-7xl mx-auto px-3 sm:px-6 py-4 sm:py-6 space-y-4 sm:space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900 dark:bg-slate-900 light:bg-white border border-slate-800 dark:border-slate-800 light:border-slate-300 p-4 sm:p-5 rounded-2xl shadow-xl transition-colors">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-lg sm:text-xl font-bold text-white dark:text-white light:text-slate-900 tracking-tight">
              {t('backup.title')}
            </h1>
            <span className="text-xs px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 light:text-emerald-700 font-mono">
              Firebase Synced
            </span>
          </div>
          <p className="text-xs text-slate-400 light:text-slate-600">
            {t('backup.sub')}
          </p>
        </div>

        <button
          onClick={handlePrintAuditReport}
          className="flex items-center gap-1.5 px-3.5 py-2 bg-slate-800 dark:bg-slate-800 light:bg-slate-100 hover:bg-slate-750 text-slate-200 light:text-slate-800 text-xs font-semibold rounded-xl border border-slate-700 light:border-slate-300 transition-colors self-start md:self-auto cursor-pointer"
        >
          <Printer className="w-4 h-4" />
          <span>{t('backup.print')}</span>
        </button>
      </div>

      {restoreSuccess && (
        <div className="p-4 rounded-xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-200 light:text-emerald-900 text-xs flex items-center gap-2">
          <Check className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{restoreSuccess}</span>
        </div>
      )}

      {restoreError && (
        <div className="p-4 rounded-xl bg-rose-500/20 border border-rose-500/40 text-rose-200 light:text-rose-900 text-xs flex items-center gap-2">
          <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
          <span>{restoreError}</span>
        </div>
      )}

      {/* Main Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6">
        
        {/* Full JSON Snapshot */}
        <div className="bg-slate-900 dark:bg-slate-900 light:bg-white border border-slate-800 dark:border-slate-800 light:border-slate-300 rounded-2xl p-5 sm:p-6 flex flex-col justify-between shadow-sm">
          <div>
            <div className="w-12 h-12 rounded-xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center mb-4">
              <HardDriveDownload className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-base text-white dark:text-white light:text-slate-900 mb-1">{t('backup.jsonTitle')}</h3>
            <p className="text-xs text-slate-400 light:text-slate-600 mb-4 leading-relaxed text-start">
              Downloads complete raw snapshot including all websites, bug issues, screenshot crop payloads, fixer handoff trails, and team configurations.
            </p>
            <div className="text-[11px] text-slate-500 space-y-1 mb-6 text-start">
              <div>Websites: <span className="text-slate-300 dark:text-slate-300 light:text-slate-700 font-mono">{websites.length} environments</span></div>
              <div>Issues: <span className="text-slate-300 dark:text-slate-300 light:text-slate-700 font-mono">{issues.length} records</span></div>
              <div>Members: <span className="text-slate-300 dark:text-slate-300 light:text-slate-700 font-mono">{teamMembers.length} users</span></div>
            </div>
          </div>

          <button
            onClick={handleDownloadJSON}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-xl shadow-md shadow-indigo-600/25 transition-all cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>{t('backup.downloadJson')}</span>
          </button>
        </div>

        {/* CSV Spreadsheet Export */}
        <div className="bg-slate-900 dark:bg-slate-900 light:bg-white border border-slate-800 dark:border-slate-800 light:border-slate-300 rounded-2xl p-5 sm:p-6 flex flex-col justify-between shadow-sm">
          <div>
            <div className="w-12 h-12 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center mb-4">
              <FileSpreadsheet className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-base text-white dark:text-white light:text-slate-900 mb-1">{t('backup.csvTitle')}</h3>
            <p className="text-xs text-slate-400 light:text-slate-600 mb-4 leading-relaxed text-start">
              Export filtered issues from <span className="text-slate-200 dark:text-slate-200 light:text-slate-800 font-medium">"{activeWebsite?.name}"</span> formatted for import into Excel, Sheets, Linear, or Jira.
            </p>
            <div className="text-[11px] text-slate-500 space-y-1 mb-6 text-start">
              <div>Format: <span className="text-slate-300 dark:text-slate-300 light:text-slate-700 font-mono">RFC 4180 CSV</span></div>
              <div>Scope: <span className="text-slate-300 dark:text-slate-300 light:text-slate-700 font-mono">{activeWebsite?.name}</span></div>
            </div>
          </div>

          <button
            onClick={handleDownloadCSV}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-xl shadow-md shadow-emerald-600/25 transition-all cursor-pointer"
          >
            <FileSpreadsheet className="w-4 h-4" />
            <span>{t('backup.downloadCsv')}</span>
          </button>
        </div>

        {/* Disaster Recovery Restore */}
        <div className="bg-slate-900 dark:bg-slate-900 light:bg-white border border-slate-800 dark:border-slate-800 light:border-slate-300 rounded-2xl p-5 sm:p-6 flex flex-col justify-between shadow-sm">
          <div>
            <div className="w-12 h-12 rounded-xl bg-rose-500/20 text-rose-400 flex items-center justify-center mb-4">
              <RefreshCw className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-base text-white dark:text-white light:text-slate-900 mb-1">{t('backup.restoreTitle')}</h3>
            <p className="text-xs text-slate-400 light:text-slate-600 mb-4 leading-relaxed text-start">
              Reconstruct and restore your QA database from a previously exported ARD JSON backup file.
            </p>
            <div className="p-3 bg-rose-500/10 border border-rose-500/30 rounded-xl text-[11px] text-rose-200 light:text-rose-900 mb-6 text-start">
              ⚠️ Restoring replaces currently staged issues with the backup dataset.
            </div>
          </div>

          <label className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-slate-800 dark:bg-slate-800 light:bg-slate-100 hover:bg-slate-700 text-slate-200 light:text-slate-800 border border-slate-700 dark:border-slate-700 light:border-slate-300 text-xs font-semibold rounded-xl transition-all cursor-pointer">
            <Upload className="w-4 h-4 text-indigo-400" />
            <span>{t('backup.selectRestore')}</span>
            <input
              type="file"
              accept=".json"
              onChange={handleRestoreFile}
              className="hidden"
            />
          </label>
        </div>

      </div>

      {/* GitHub Pages Deployment Banner */}
      <div className="mt-8 bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 dark:from-slate-900 dark:via-indigo-950/40 dark:to-slate-900 light:from-white light:via-indigo-50/60 light:to-white border border-indigo-500/30 rounded-2xl p-5 sm:p-6 flex flex-col md:flex-row items-center justify-between gap-4 shadow-xl">
        <div className="flex items-center gap-4 text-start">
          <div className="w-12 h-12 rounded-xl bg-slate-800 dark:bg-slate-800 light:bg-slate-200 border border-slate-700 dark:border-slate-700 light:border-slate-300 flex items-center justify-center text-white light:text-slate-900 shadow-inner shrink-0">
            <Github className="w-6 h-6" />
          </div>
          <div>
            <h4 className="font-bold text-sm sm:text-base text-white dark:text-white light:text-slate-900 flex items-center gap-2">
              <span>{language === 'fa' ? 'استقرار و انتشار روی GitHub Pages' : language === 'ps' ? 'په GitHub Pages کې خپرول او ځای پر ځای کول' : 'Publish & Host on GitHub Pages'}</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 font-mono border border-emerald-500/30">
                CI/CD Ready
              </span>
            </h4>
            <p className="text-xs text-slate-400 dark:text-slate-400 light:text-slate-600 mt-0.5">
              {language === 'fa' 
                ? 'پروژه آماده ارسال به ریپازیتوری شماست. گردش‌کار خودکار GitHub Actions، مسیرهای نسبی Vite و هندلر ۴۰۴ فعال شده‌اند.' 
                : language === 'ps' 
                ? 'پروژه ستاسو ریپوزیټري ته د استولو لپاره چمتو دی. د GitHub Actions اتومات جریان او نسبي لارې فعالې دي.' 
                : 'Project is configured with Vite relative base paths (./), GitHub Actions CI/CD workflow, and SPA 404 handler for instant hosting.'}
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowGhModal(true)}
          className="w-full md:w-auto flex items-center justify-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-xl shadow-lg shadow-indigo-600/25 transition-all cursor-pointer shrink-0"
        >
          <Github className="w-4 h-4" />
          <span>{language === 'fa' ? 'مشاهده راهنمای انتشار GitHub Pages' : language === 'ps' ? 'د GitHub Pages لارښود کتل' : 'Deploy to GitHub Pages'}</span>
        </button>
      </div>

      {/* GitHub Pages Modal */}
      <GitHubPagesModal
        isOpen={showGhModal}
        onClose={() => setShowGhModal(false)}
      />

    </div>
  );
};
